#!/bin/python

from time import sleep
from sys import argv, exit, stdout

BATTERY_PATH = '/sys/class/power_supply/BAT0/'

if len(argv) > 1:
    PREFIX = argv[1]
else:
    PREFIX = ''


def get_battery_charge(path):
    with open(path + 'energy_full') as f:
       capacity = int(f.read())
    with open(path + 'energy_now') as f:
       current_charge = int(f.read())

    charge = int(current_charge / capacity * 100)
    return str(charge)

def main():
    while True:
        print(PREFIX +
              get_battery_charge(BATTERY_PATH) +
              '%')
        stdout.flush()
        sleep(60)

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        exit()
