#!/bin/env python
# A clock that updates every minute. Pass it a string as
# the first argument to prepend it to the output. This is
# useful for parsing the output with panel makers, etc.

from time import strftime, sleep, localtime
from sys import argv, exit, stdout

if len(argv) > 1:
    PREFIX = argv[1]
else:
    PREFIX = ''

DATE_FORMAT = PREFIX + '%a %d %b, %H:%M'

def main():
    while True:
        print(strftime(DATE_FORMAT), flush=True)
        time = localtime()
        seconds_to_sleep = 60 - time.tm_sec
        sleep(seconds_to_sleep)


if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        exit()
