#!/bin/sh
# Get date from HTTP server

SERVER="ub.edu"

if [[ ! $(whoami) == root ]]; then
	echo "ERROR> This script must be run as root."
	exit 1
fi

get_date() {
	curl -sI "${SERVER}" \
		| grep '^Date:' \
		| cut -d' ' -f3-6
}

DATE="$(get_date)Z"
test -n $DATE && date -s "$DATE"
