#!/bin/sh

_get_cur_layout() {
    regex="layout: +(\w\w)"
    setxkbmap -query | pcregrep -o1 "$regex"
}

if [[ "$1" == "get" ]]; then
    echo $(_get_cur_layout)
    exit 0
else
    case $(_get_cur_layout) in
        es) setxkbmap us
            xmodmap ~/.Xmodmaprc
            xmodmap -e "keysym Alt_R = Hangul"
            _fifo_output "$(_get_cur_layout)"
            ;;

        us) setxkbmap es
            xmodmap ~/.Xmodmaprc
            _fifo_output "$(_get_cur_layout)"
            ;;
    esac
fi


# vim: sts=4 ts=4 et sw=4
