#!/usr/bin/env python
import os
import json
import argparse

"""
A simple bookmark searcher.
"""

parser = argparse.ArgumentParser()
parser.add_argument('--file', '-f', help="Bookmarks file", default="~/.bookmarks")
parser.add_argument('--tag', '-g', help="Find by tag")
parser.add_argument('--uri', '-u', help="Find by URI")
parser.add_argument('--title', '-t', help="Find by title")
args = parser.parse_args()

req_tag, req_title, req_uri, file = args.tag, args.title, args.uri, args.file

with open(os.path.expanduser(file)) as f:
    json_struct = json.load(f)

    if req_tag is not None:
        for entry in json_struct:
            if req_tag in entry.get('tags'):
                print(entry.get('uri'))

    if req_title is not None:
        for entry in json_struct:
            if req_title in entry.get('title'.lower()):
                print(entry.get('uri'))

    if req_uri is not None:
        for entry in json_struct:
            if req_uri in entry.get('uri'):
                print(entry.get('uri'))
