#!/bin/sh

IN=eth0
OUT=wlan0

echo 1 > /proc/sys/net/ipv4/ip_forward
iptables -t nat -A POSTROUTING -o $OUT -j MASQUERADE
iptables -A FORWARD -i $IN -o $OUT -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -A FORWARD -i $IN -o $OUT -j ACCEPT
