#!/bin/sh

IN=wlan0
OUT=eth0

echo 1 > /proc/sys/net/ipv4/ip_forward
iptables -t nat -A POSTROUTING -o $IN -j MASQUERADE
iptables -A FORWARD -i $IN -o $OUT -j ACCEPT
iptables -A FORWARD -i $OUT -o $IN -j ACCEPT
