#!/usr/bin/env python3
# A script that will start and manage the processes
# that feed the dzen2 panel

import signal
import subprocess
import os
import sys

fifo = '/tmp/panel.fifo'
home = os.getenv('HOME')

apps = {'clock': 'clock D',
        'keyboard': 'kbdlayout get',
        'panel_parser': 'panel_parser',
        'battery': 'battery B',
        'mail': 'inbox_watcher {0}/mail/inbox M'.format(home),
        'bspwm_status': 'bspc control --subscribe',
        'win_title': 'xtitle -sf T%s'
        }

enabled_apps = ['bspwm_status',
                'battery',
                'mail',
                'clock',
                'win_title']

active_apps = []


def main():
    """ Start all the processes in the "enabled_apps" list. """
    if not os.path.exists(fifo):
        os.mkfifo(fifo)

    with open(fifo, mode='w') as f:
        for app in enabled_apps:
            command = apps[app].split()
            print(command)

            # Spawn the process
            child = subprocess.Popen(command,
                                     stdout=f,
                                     universal_newlines=True,
                                     stdin=None)
            print('Started', app, '(' + str(child.pid) + ')', flush=True)
            active_apps.append(child)

        subprocess.call(apps['keyboard'].split(), stdout=f)
        for app in active_apps:
            app.wait()


def check():
    """ Check if another instance is running. """
    pgrep = subprocess.call(["pgrep", "panel_feeder"])
    if pgrep == 1:
        return True


def die():
    for app in active_apps:
        print('Killing', app, flush=True)
        app.kill()

    print('Cleaning up...', flush=True)
    os.remove(fifo)
    print('Bye!', flush=True)
    sys.exit()

if __name__ == '__main__':
    if check():
        signal.signal(signal.SIGTERM, die)
        try:
            main()
        except KeyboardInterrupt:
            die()
    else:
        sys.exit('ERROR: Another instance of the panel is already running.')
