#!/bin/sh

source ~/.panelrc

if [ $(pgrep -u $USER -cx panel) -gt 1 ] ; then
	echo "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

if [ -e "$PANEL_FIFO" ]; then
	rm "$PANEL_FIFO"
	mkfifo "$PANEL_FIFO"
else
	mkfifo "$PANEL_FIFO"
fi

bspc config top_padding $PANEL_HEIGHT
bspc control --subscribe > "$PANEL_FIFO" &
xtitle -sf 'T%s' > "$PANEL_FIFO" &
clock -sf 'S%a %H:%M' > "$PANEL_FIFO" &

cat "$PANEL_FIFO" \
	| panel_parser \
	| bar \
		-f "$PANEL_FONT_FAMILY" \
		-F "$COLOR_DEFAULT_FG" \
		-B "$COLOR_DEFAULT_BG" &

wait

rm "$PANEL_FIFO"
