#!/bin/bash

CHECK_DIR="$HOME/mail/inbox/new"
PREFIX=$1

while true; do
	OUT=$(find "$CHECK_DIR" -type f | wc -l)
	if [[ "$OUT" == "0" ]]; then
		echo "${PREFIX}"
	else
		echo ${PREFIX}${OUT}
	fi

	sleep 15
done
